### ISSUE TITLE
add the usecase page

### ISSUE THREAD

**Issue by aiB0ld** [UIUC-DDDG-AR/StarMap#45]

**Comment by mingiryu** [comment]
# Initial Design

![ar-capabilities](https://user-images.githubusercontent.com/40753283/86975856-e279fd00-c13e-11ea-9664-4a56792feee1.png)
![ar-capabilities(1)](https://user-images.githubusercontent.com/40753283/86975858-e443c080-c13e-11ea-9f2f-95afe034fbe2.png)
![ar-capabilities(2)](https://user-images.githubusercontent.com/40753283/86975861-e4dc5700-c13e-11ea-8115-a8f2ce7bb1e0.png)

**Comment by mingiryu** [comment]
For displaying the table, [Material UI Tables component](https://material-ui.com/components/tables/) might be useful.
